# Login page
email = "cmuuser1test@mobile.ukti.gov.uk"
pwd = "Essex040"
userName = "username"
password = "password"
loginButton = "//button[@type='submit']"
logoutButton = "//a[contains(@href, 'signout')]"
searchField = "search"
searchSubmit = "//input[@type='submit']"
parent_company_search_field = "search-term"
addNewCompanyButton = "//a[contains(@href, '/company/add-step-1/')]"
companyList = ".//*[@id='main-content']/div/article/ol/li[{}]"
companyListNames = ".//*[@id='main-content']/div/article/ol/li[1]/h3/a/span"
parent_company_list = ".//*[@id='main-content']/div/article/ol/li[1]/a/h3"
parent_company_choose_button = ".//*[@id='main-content']/div/article/ol/li[1]/div/a"
conpanyDetailsTab = "//nav/a[contains(@href, 'ltd')]"
companyHierarchyTab = "//nav/a[contains(@href, 'hierarchy')]"
contactsTab = "//nav/a[contains(@href, 'contacts')]"
interactionsTab = "//nav/a[contains(@href, 'interactions')]"
documentsTab = "//nav/a[contains(@href, 'documents')]"
exportTab = "//nav/a[contains(@href, 'export')]"
investmentTab = "//nav/a[contains(@href, 'investment')]"

# Company Summary
companyTitle = ".//*[@id='main-content']/h2"
companyAddress = ".//*[@id='main-content']/h2/span"
companySummaryListTitles = "//table[@id='cdms-details']/tbody/tr[{}]/th"
companySummaryListDetails = "//table[@id='cdms-details']/tbody/tr[{}]/td"
editButton = "//a[contains(@href, 'edit')]"

# Contacts
addNewContactButton = "add-contact-link"

# Create New Company
uk_limitedcompany_radiobutton = "ltd"
othertypeofukorganisation_radiobutton = "ukother"
foreign_organisation_radiobutton = "foreign"
typeOfOrganisation_foreign = "business_type_for_other"
typeOfOrganisation_other_uk = "business_type_uk_other"
companyName = "name"
tradingName = "alias"
addressLine1 = "registered_address_1"
addressLine2 = "registered_address_2"
town = "registered_address_town"
county = "registered_address_county"
postcode = "registered_address_postcode"
country = "registered_address_country"
addTradingAddressButton = "add-trading-address"
tradingAddressLine1 = "trading_address_1"
tradingAddressLine2 = "trading_address_2"
tradingTown = "trading_address_town"
tradingCounty = "trading_address_county"
tradingPostcode = "trading_address_postcode"
tradingCountry = "trading_address_country"
headquarters = ".//*[@id='headquarters-wrapper']/label[{}]/input"
sector = ".//*[@id='main-content']/div/article/form/div[5]/select"
sectorItem = ".//*[@id='main-content']/div/article/form/div[5]/select/option[13]"
website = "website"
businessDescription = "description"
numberOfEmployees = "employee_range"
annualTurnover = "turnover_range"

# Postcodelookup

primary_uk_postcode = ".//*[@id='{}-address-wrapper']/div[2]/input"
primary_find_uk_address = ".//*[@id='{}-address-wrapper']/div[2]/button"
primary_select_an_uk_address_dropdown = ".//*[@id='{}-address-wrapper']/div[3]/select"
primary_select_an_uk_address_from_list = ".//*[@id='{}-address-wrapper']/div[3]/select/option[2]"
trading_uk_postcode = ".//*[@id='trading-address-wrapper']/div[1]/input"
trading_find_uk_address = ".//*[@id='trading-address-wrapper']/div[1]/button"
trading_select_an_uk_address_dropdown = ".//*[@id='trading-address-wrapper']/div[2]/select"
trading_select_an_uk_address_from_list = ".//*[@id='trading-address-wrapper']/div[2]/select/option[2]"
uk_region = "uk_region"

def fill_out_the_login_form(driver):
    driver.find_element_by_id(userName).send_keys(email)